include:
  - board: rpi_pico2/rp2350a/m33
    shield: piantor_pico2_left_test
    artifact-name: piantor_pico2_left_test
  - board: rpi_pico2/rp2350a/m33
    shield: piantor_pico2_right_test
    artifact-name: piantor_pico2_right_test
